--
-- Database: `bot`
--

-- --------------------------------------------------------

--
-- Table structure for table `chatbot`
--

DROP TABLE IF EXISTS `chatbot`;
CREATE TABLE IF NOT EXISTS `chatbot` (
  `id` int NOT NULL AUTO_INCREMENT,
  `queries` varchar(255) NOT NULL,
  `replies` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=153 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `chatbot`
--

INSERT INTO `chatbot` (`id`, `queries`, `replies`) VALUES
(5, 'hi', 'Hello! How can I assist you today?'),
(4, 'hello', 'Hi there! How can I help you?'),
(6, 'how are you', 'I am just a bot, but I am doing great!'),
(7, 'bye', 'Goodbye! Have a great day!'),
(8, 'what is your name', 'I am a chatbot created to assist you.'),
(9, 'who created you', 'I was created by a developer to help answer your queries.'),
(10, 'tell me a joke', 'Why did the scarecrow win an award? Because he was outstanding in his field!'),
(11, 'what can you do', 'I can answer your queries, tell jokes, and provide basic assistance.'),
(12, 'thank you', 'You are welcome!'),
(13, 'how old are you', 'I am as old as the internet!'),
(14, 'what is the capital of France', 'The capital of France is Paris.'),
(15, 'who is the president of USA', 'It depends on the current year. You can check the latest news for updates.'),
(16, 'what is the weather today', 'I am not connected to real-time data, but you can check a weather website.'),
(17, 'do you like music', 'I do not have ears, but I appreciate music in theory!'),
(18, 'who is your favorite actor', 'I do not watch movies, but I hear Leonardo DiCaprio is great!'),
(19, 'can you dance', 'I can dance with words!'),
(20, 'what is 2+2', '2+2 is 4.'),
(21, 'what is the meaning of life', 'The meaning of life is a philosophical question, but many say it is 42!'),
(22, 'where is the Eiffel Tower', 'The Eiffel Tower is in Paris, France.'),
(23, 'what is AI', 'AI stands for Artificial Intelligence, which allows machines to mimic human thinking.'),
(24, 'tell me a fun fact', 'Did you know honey never spoils?'),
(25, 'who is the CEO of Google', 'As of recent times, Sundar Pichai is the CEO of Google.'),
(26, 'what is the largest ocean', 'The Pacific Ocean is the largest ocean in the world.'),
(27, 'who won the last FIFA World Cup', 'You can check FIFA’s official website for the latest winners.'),
(28, 'what is the fastest animal', 'The peregrine falcon is the fastest animal, reaching speeds over 240 mph.'),
(29, 'how many continents are there', 'There are seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.'),
(30, 'who wrote Harry Potter', 'J.K. Rowling wrote the Harry Potter series.'),
(31, 'what is the tallest mountain', 'Mount Everest is the tallest mountain in the world.'),
(32, 'who is the richest person', 'This changes frequently, but you can check Forbes for the latest updates.'),
(33, 'how to lose weight', 'Eat healthy, exercise regularly, and maintain a balanced diet.'),
(34, 'what is the speed of light', 'The speed of light is approximately 299,792,458 meters per second.'),
(35, 'what is the square root of 16', 'The square root of 16 is 4.'),
(36, 'who invented the telephone', 'Alexander Graham Bell invented the telephone.'),
(37, 'when was the first computer made', 'The first modern computer was developed in the 1940s.'),
(38, 'where is the Great Wall of China', 'The Great Wall of China is in China.'),
(39, 'what is photosynthesis', 'Photosynthesis is the process by which plants make their own food using sunlight.'),
(40, 'who is the best football player', 'This is a matter of opinion, but players like Messi and Ronaldo are often considered among the best.'),
(41, 'how to make money online', 'There are many ways, such as freelancing, e-commerce, and content creation.'),
(42, 'what is cryptocurrency', 'Cryptocurrency is a digital currency secured by cryptography, such as Bitcoin and Ethereum.'),
(43, 'who was Albert Einstein', 'Albert Einstein was a physicist famous for his theory of relativity.'),
(44, 'what is the biggest planet in the solar system', 'Jupiter is the largest planet in the solar system.'),
(45, 'who was the first person on the moon', 'Neil Armstrong was the first person to walk on the moon in 1969.'),
(46, 'what is gravity', 'Gravity is the force that pulls objects toward each other, like keeping us on Earth.'),
(47, 'how to cook pasta', 'Boil water, add pasta, cook for 8-10 minutes, drain, and add sauce.'),
(48, 'who discovered America', 'Christopher Columbus is often credited with discovering America in 1492.'),
(49, 'what is the best programming language', 'It depends on your needs, but popular ones include Python, JavaScript, and C++.'),
(50, 'how to be successful', 'Work hard, stay consistent, and keep learning.'),
(51, 'who invented the airplane', 'The Wright brothers invented the airplane.'),
(52, 'what is a black hole', 'A black hole is a region in space where gravity is so strong that nothing can escape.'),
(53, 'what is the longest river', 'The Nile River is the longest river in the world.'),
(54, 'how does the internet work', 'The internet works by transmitting data through networks using protocols like TCP/IP.'),
(55, 'what is 10 factorial', '10! (10 factorial) is 3,628,800.'),
(56, 'why is the sky blue', 'The sky appears blue due to Rayleigh scattering of sunlight in the atmosphere.'),
(57, 'who is the father of computers', 'Charles Babbage is known as the father of the computer.'),
(58, 'what is blockchain', 'Blockchain is a decentralized ledger technology used in cryptocurrencies like Bitcoin.'),
(59, 'who painted the Mona Lisa', 'Leonardo da Vinci painted the Mona Lisa.'),
(60, 'what is the hardest natural substance', 'Diamond is the hardest natural substance.'),
(61, 'how do airplanes fly', 'Airplanes fly using the principles of lift, thrust, drag, and weight.'),
(62, 'who was the first President of the USA', 'George Washington was the first President of the USA.'),
(63, 'what is the human body made of', 'The human body is made of cells, which contain water, proteins, fats, and minerals.'),
(64, 'how long does it take to reach the moon', 'It takes about 3 days to reach the moon from Earth.'),
(65, 'how do birds fly', 'Birds fly using their wings to generate lift and thrust.'),
(66, 'what is DNA', 'DNA is the molecule that carries genetic information in living organisms.'),
(67, 'what is the smallest country in the world', 'Vatican City is the smallest country in the world.'),
(68, 'who invented the light bulb', 'Thomas Edison is credited with inventing the practical light bulb.'),
(69, 'how deep is the ocean', 'The deepest part of the ocean is the Mariana Trench, which is about 36,000 feet deep.'),
(70, 'what is the population of the world', 'The world population is over 8 billion as of recent estimates.'),
(71, 'how do volcanoes erupt', 'Volcanoes erupt when magma rises through cracks in the Earth’s crust.'),
(72, 'what is the coldest place on Earth', 'Antarctica is the coldest place on Earth.'),
(73, 'who wrote Romeo and Juliet', 'William Shakespeare wrote Romeo and Juliet.'),
(74, 'what is the difference between weather and climate', 'Weather is short-term atmospheric conditions, while climate is the average over a long period.'),
(75, 'how do fish breathe', 'Fish breathe through gills that extract oxygen from water.'),
(76, 'what is the national animal of India', 'The national animal of India is the Bengal tiger.'),
(77, 'who discovered gravity', 'Isaac Newton is credited with discovering gravity.'),
(78, 'what is the boiling point of water', 'Water boils at 100°C (212°F) at sea level.'),
(79, 'how do plants grow', 'Plants grow using sunlight, water, and nutrients from the soil through photosynthesis.'),
(80, 'how do magnets work', 'Magnets work due to the movement of electrons, creating a magnetic field.'),
(81, 'what is a solar eclipse', 'A solar eclipse occurs when the moon passes between the Earth and the sun, blocking sunlight.'),
(82, 'what is a lunar eclipse', 'A lunar eclipse happens when the Earth casts a shadow on the moon.'),
(83, 'how far is the sun from Earth', 'The sun is approximately 93 million miles (150 million km) from Earth.'),
(84, 'what is the tallest building in the world', 'The Burj Khalifa in Dubai is the tallest building in the world.'),
(85, 'what is a tsunami', 'A tsunami is a series of ocean waves caused by underwater earthquakes or volcanic eruptions.'),
(86, 'who discovered electricity', 'Benjamin Franklin is often credited with discovering electricity.'),
(87, 'what is a galaxy', 'A galaxy is a large system of stars, gas, and dust bound together by gravity.'),
(88, 'how many bones are in the human body', 'An adult human has 206 bones.'),
(89, 'how do earthquakes happen', 'Earthquakes happen due to the movement of tectonic plates in the Earth’s crust.'),
(90, 'what is the Big Bang Theory', 'The Big Bang Theory explains the origin of the universe as a rapid expansion from a singularity.'),
(91, 'who invented the internet', 'The internet was developed by multiple scientists, including Vinton Cerf and Bob Kahn.'),
(92, 'what is the smallest planet in the solar system', 'Mercury is the smallest planet in the solar system.'),
(93, 'what is the largest desert in the world', 'The Antarctic Desert is the largest desert by area.'),
(94, 'how does a camera work', 'A camera captures light through a lens, focusing it onto a sensor or film.'),
(95, 'what is the longest railway in the world', 'The Trans-Siberian Railway is the longest railway line.'),
(96, 'how do computers store data', 'Computers store data using binary code (0s and 1s) in memory and storage devices.'),
(97, 'who wrote The Lord of the Rings', 'J.R.R. Tolkien wrote The Lord of the Rings.'),
(98, 'what is a volcano', 'A volcano is an opening in the Earth’s crust that allows magma to escape as lava.'),
(99, 'what is the difference between a virus and bacteria', 'Viruses require a host to replicate, while bacteria can live and multiply independently.'),
(100, 'who painted The Starry Night', 'Vincent van Gogh painted The Starry Night.'),
(101, 'what is the longest word in the dictionary', 'The longest word is often considered \"pneumonoultramicroscopicsilicovolcanoconiosis.\"'),
(102, 'how do planes stay in the air', 'Planes stay in the air due to lift generated by their wings.'),
(103, 'who is the current prime minister of the UK', 'You can check the latest news for the current Prime Minister of the UK.'),
(104, 'how many teeth does an adult human have', 'An adult human typically has 32 teeth.'),
(105, 'what is a rainbow', 'A rainbow is formed when sunlight is refracted and reflected in water droplets.'),
(106, 'who is the fastest person in the world', 'Usain Bolt holds the record for the fastest 100m sprint.'),
(107, 'what is the largest lake in the world', 'The Caspian Sea is the largest lake by surface area.'),
(108, 'how long is a day on Mars', 'A day on Mars, called a \"sol,\" is about 24 hours and 39 minutes.'),
(109, 'how deep is the Grand Canyon', 'The Grand Canyon is about 6,093 feet (1,857 meters) deep.'),
(110, 'what is the coldest planet in the solar system', 'Neptune is the coldest planet in the solar system.'),
(111, 'who discovered penicillin', 'Alexander Fleming discovered penicillin in 1928.'),
(112, 'what is a black hole', 'A black hole is a region in space where gravity is so strong that nothing can escape.'),
(113, 'how many moons does Jupiter have', 'Jupiter has at least 79 known moons.'),
(114, 'what is the largest animal in the world', 'The blue whale is the largest animal in the world.'),
(115, 'how does the brain work', 'The brain processes information using neurons that send electrical and chemical signals.'),
(116, 'who discovered oxygen', 'Joseph Priestley and Carl Scheele are credited with discovering oxygen.'),
(117, 'how do vaccines work', 'Vaccines help build immunity by exposing the body to a harmless part of a virus or bacteria.'),
(118, 'who invented paper', 'The Chinese inventor Cai Lun is credited with inventing paper.'),
(119, 'what is a comet', 'A comet is a celestial body made of ice and dust that orbits the sun.'),
(120, 'how do birds migrate', 'Birds migrate by using environmental cues, the sun, and the Earth’s magnetic field.'),
(121, 'how do submarines work', 'Submarines control buoyancy using ballast tanks filled with water or air.'),
(122, 'what is the oldest civilization', 'The Sumerians of Mesopotamia are considered one of the oldest civilizations.'),
(123, 'what is a leap year', 'A leap year has 366 days and occurs every four years to align with Earth’s orbit.'),
(124, 'who invented the television', 'John Logie Baird is credited with inventing the television.'),
(125, 'what is the driest place on Earth', 'The Atacama Desert in Chile is the driest place on Earth.'),
(126, 'how do plants make oxygen', 'Plants release oxygen as a byproduct of photosynthesis.'),
(127, 'who is the tallest person ever recorded', 'Robert Wadlow, at 8 feet 11 inches, is the tallest person ever recorded.'),
(128, 'what is the most expensive metal', 'Rhodium is one of the most expensive metals.'),
(129, 'how do bees make honey', 'Bees collect nectar, process it with enzymes, and store it in honeycombs.'),
(130, 'who invented the radio', 'Guglielmo Marconi is credited with inventing the radio.'),
(131, 'what is the brightest star in the night sky', 'Sirius is the brightest star in the night sky.'),
(132, 'who invented the first car', 'Karl Benz is credited with inventing the first modern car.'),
(133, 'how do fish sleep', 'Fish rest but do not sleep like humans; they reduce their activity level.'),
(134, 'who wrote The Great Gatsby', 'F. Scott Fitzgerald wrote The Great Gatsby.'),
(135, 'how do touchscreens work', 'Touchscreens detect touch using capacitive or resistive technology.'),
(136, 'who discovered Pluto', 'Clyde Tombaugh discovered Pluto in 1930.'),
(137, 'what is the heaviest land animal', 'The African elephant is the heaviest land animal.'),
(138, 'how do ships float', 'Ships float due to the principle of buoyancy and displacement of water.'),
(139, 'what is the national sport of Canada', 'Lacrosse and ice hockey are considered the national sports of Canada.'),
(140, 'how does a battery work', 'Batteries store chemical energy and convert it into electrical energy.'),
(141, 'who built the Taj Mahal', 'Emperor Shah Jahan built the Taj Mahal in memory of his wife.'),
(142, 'what is a supernova', 'A supernova is a powerful explosion of a dying star.'),
(143, 'who invented the microscope', 'Zacharias Janssen is credited with inventing the microscope.'),
(144, 'what is the largest organ in the human body', 'The skin is the largest organ in the human body.'),
(145, 'who wrote To Kill a Mockingbird', 'Harper Lee wrote To Kill a Mockingbird.'),
(146, 'how long can a person go without water', 'A person can survive about 3 days without water.'),
(147, 'who is the founder of Microsoft', 'Bill Gates and Paul Allen founded Microsoft.'),
(148, 'what is the main ingredient in chocolate', 'Cocoa beans are the main ingredient in chocolate.'),
(149, 'how many planets are in the solar system', 'There are 8 planets in the solar system.'),
(150, 'what is the smallest bird', 'The bee hummingbird is the smallest bird in the world.'),
(151, 'what is the loudest animal', 'The sperm whale is the loudest animal.'),
(152, 'what is the speed of sound', 'The speed of sound is about 343 meters per second in air.');

